name: Deploy MkDocs site to GitHub Pages

on:
  # Se déclenche lors des push sur la branche par défaut
  push:
    branches: ["main"] # ou "master"

  # Permet de lancer ce workflow manuellement depuis l'onglet Actions
  workflow_dispatch:

# Définit les permissions pour permettre le déploiement sur GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Ne permet qu'un seul déploiement simultané
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job de construction
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install mkdocs-material # Ajoutez d'autres plugins ici si besoin
      - name: Build with MkDocs
        run: mkdocs build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site'

  # Job de déploiement
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
